name: konekseed_test
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=3.2.4 <4.0.0"

dependencies:
    custom_sliding_segmented_control: ^1.8.1
    dropdown_button2: ^2.3.9
    flutter:
        sdk: flutter
    flutter_advanced_segment: ^3.0.2
    flutter_localizations:
        sdk: flutter
    image_picker: ^1.0.7
    intl: ^0.18.1
    stylish_bottom_bar: ^1.0.3

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/images/
