name: konekseed_test
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=3.2.4 <4.0.0"

dependencies:
    custom_sliding_segmented_control: ^1.8.1
    dropdown_button2: ^2.3.9
    email_validator: ^2.1.17
    flutter:
        sdk: flutter
    freezed_annotation: ^2.4.1
    image_picker: ^1.0.7
    intl: ^0.18.1
    json_annotation: ^4.8.1
    stylish_bottom_bar: ^1.0.3
    cloud_firestore: ^4.13.1
    firebase_storage: ^11.5.1
    firebase_core: ^2.22.0
    firebase_auth: ^4.14.0
    fpdart: ^1.1.0
    flutter_riverpod: ^2.4.10
    uuid: ^4.3.3

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0
    build_runner: ^2.4.8
    freezed: ^2.4.7
    json_serializable: ^6.7.1
    analyzer: ^5.11.1

flutter:
    uses-material-design: true

    assets:
        - assets/images/
